### PR TITLE
Find files in Windows

### PR DESCRIPTION
**Pull request by jgsogo**
Using [C++ Request](https://github.com/skystrife/cpr) from @skystrife I come accross an issue related to installation in Windows (it may happen also in other platforms). With this fix the system is able to found the files to install.

I'm pushing the PR here because it is the repo being used as dependency in skystrife/cpr, but I'll try to push it also upstream to bagder/curl.

Thanks!

### CODE REVIEW

**Comment by whoshuu** [comment]
Thanks for the PR @jgsogo. That's an interesting find. `CURL_BINARY_DIR` and `CMAKE_BINARY_DIR` _should_ be the same, but I guess they aren't. I'll run this through appveyor and let you know if it's good to go.

**Comment by whoshuu** [comment]
Looks good to me. Thanks!

**Comment by whoshuu** [comment]
The change is reflected in the main C++ Requests repository here: https://github.com/whoshuu/cpr/commit/f9a3159d0363670a50cba5331c9405b3f3ef824c. Note, the fork you're using from @skystrife will have to pull in the changes before you see them. Alternatively you can fork the main repository yourself.

**Comment by jgsogo** [comment]
Thanks! I don't know why I was using @skystrife's repo, maybe because I'm interested in [META](https://github.com/meta-toolkit/meta) and I had a look at his profile... I'll move to yours.

**Pull request merged**
